name: build app 

on: 
  push:
    branches: [master,main]
  pull_request:
    branches: [master,main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install         
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_JAVASCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: tells whether it succeeded 
        run: echo "this workflows works"
